Form validation implemented according to specification
kkolade/kolakolade.me pull request #17
Opened 2022-11-24 21:48 UTC by kkolade

## The form validation is implemented: The content of the email field has to be in lowercase.
- When a user submits the form, check if the email field value is in lowercase
- If the validation is OK, the form is sent.
- If the validation is not OK,  an error message is shown to the user near the submit button informing them of the error, and the form is not sent..

2022-11-24 22:32 UTC, kkolade commented
## PR observation resolved
- Linters files fixed
- README.md updated

2022-11-24 23:49 UTC, Kossi-stack requested changes
## Hi @kkolade,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

- [ ] Kindly fix the error when i submit the form it does not go through.

https://www.loom.com/share/23415078e88746ec97a68e4427fc5850

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-25 07:47 UTC, kkolade commented
## Fix PR comment: form not submitting
- The form now submits if no error

2022-11-25 08:09 UTC, prolajumokeoni approved these changes
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Check inline comment

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 08:09 UTC, prolajumokeoni commented on index.html
>            >Write your message here</textarea>
### OPTIONAL

- [ ] Kindly add `Write your message here` as a placeholder this way users don't need to clear text before typing the message

2022-11-25 08:24 UTC, kkolade commented
## Textarea place holder issue now fixed
- The placeholder text in the textarea now clear off when user types in the textarea

2022-11-25 08:32 UTC, kkolade commented
### Fixed textarea placeholder issue:
- Placeholder text in textarea now clears when the user starts to type
@prolajumokeoni

2022-11-25 08:36 UTC, merged