Work and About me section completed
kkolade/kolakolade.me pull request #2
Opened 2022-10-28 22:18 UTC by kkolade

Finished this section by:
- Creating the HTML according to the template
- Styled the section as close to the template as possible
- Used skills acquired in the last few days including
- Flexbox, CSS Grid Positioning

2022-10-28 22:29 UTC, MaganaAsiati commented
hey How are you can you please fix the linter so that I can proceed with review

2022-10-28 23:33 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @kkolade 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- [ ] You did a great job in your design it looks nice but  Kindly makes sure your design stick as much as possible to the Figma design as it was required in the project  :100: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-28 23:33 UTC, MaganaAsiati commented on index.html
> +              </ul>
- [ ] you did a great job implementing this section it looks nice but kindly does not use pictures so that you will be able to add some style  to your language section :+1: 
- [ ] Kindly make sure you add some space between my language and language cards as it is shown below in the Figma design :+1: 

- Kindly make sure you add the skills button cause as I see in your design is not present. Your design must stick to the Figma design as much as possible :+1: 

## Figma design 
![image](https://user-images.githubusercontent.com/95297251/198749935-f80f747d-98a9-4894-be6e-6113d1d8d44e.png)

## Your design 

![image](https://user-images.githubusercontent.com/95297251/198750015-56abea36-2b3d-49ab-94d2-52e132c1f038.png)

2022-10-28 23:33 UTC, MaganaAsiati commented on index.html
> +          </div>
- [ ] Kindly make sure you add some space between see project button and languages button so that it will make your design stick to the Figma design :+1: 

## your design 

![image](https://user-images.githubusercontent.com/95297251/198750255-255e5aa8-721b-4c98-83e3-12f4ef24c16a.png)

## Figma design 

![image](https://user-images.githubusercontent.com/95297251/198750295-69f3f420-78ae-4516-b28b-84f6422ead8f.png)

2022-10-29 06:46 UTC, OyePriscilla approved these changes
# Hi @kkolade 😄 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
The commit messages are meaningful ✅
Linters are working properly ✅
Github flow observed ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @oyepriscilla in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 06:46 UTC, merged