Contact me form added to the portfolio project
kkolade/kolakolade.me pull request #4
Opened 2022-11-01 22:39 UTC by kkolade

The contact form section was added to the project and style as close to the template as possible
While executing the project, the following objectives were adhered to:

- Name field accepts up to 30 chars.
- Email field accepts only emails.
- Message field accepts up to 500 chars.
- All fields have placeholder text.
- All fields have the correct type.
- A user cannot submit the form if one or more of the fields is empty.
- Data collection by using the [Formspree service](https://formspree.io/html).
- Flexbox is used In order to lay out the elements on the page.
- Button interactions implemented as per the template(enable, hover, etc.).

2022-11-01 23:16 UTC, jaflih requested changes
Hi @kkolade , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
Correct Gitflow has been followed ✔️
Descriptive README.md file ✔️
Pull Request has a title and summary ✔️
No Linter error ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @jaflih in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 23:16 UTC, jaflih commented on css/style.css
> +}
Please add a backgroud image for Desktop and Mobile  view to stick to Figma design.

Figma: 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/7243132/199359422-fa5a9960-25d5-4dd8-8ccf-633b322f871d.png">


Your design
![Capture d’écran 2022-11-02 à 00 09 01](https://user-images.githubusercontent.com/7243132/199359375-65b3bb1e-ff2e-41d2-b707-3c3ffa9e556e.png)

2022-11-02 17:32 UTC, kkolade commented
Images added to the background of the 'Hero' and 'Contact' as per the Figma template

2022-11-02 17:43 UTC, aimalamiri requested changes
Hi @kkolade, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- The form is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 17:43 UTC, aimalamiri commented on index.html
> +        <div class="bottom_line"></div>
Good job, but it's highly recommended to follow the exact Figma template, so please make sure to remove the extra space under the bottom line.

![image](https://user-images.githubusercontent.com/34779928/199562616-161b992f-3fa3-481d-b0ea-18a46471e38f.png)

2022-11-02 18:37 UTC, kkolade commented
The extra space at the bottom of the contact section has been removed and the project is more reflective of the Figma template

2022-11-02 18:43 UTC, anagudelogu approved these changes
Hi @kkolade, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 👍🏼 
✅ Great UI design! 💯 
✅ Descriptive commit messages. 💬 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 18:47 UTC, merged